### ISSUE TITLE
The Swift demo is not in swift

### ISSUE THREAD

**Issue by bbookman** [AppLovin/iOS-SDK-Demo#19]
Take a look at the files in OS-SDK-Demo/Swift Demo App.  They are Objective-C

**Comment by thomasmso** [comment]
Hi,

Our demo apps primarily demonstrate integrations for the following types of ads your view controllers:

- [Interstitials](https://github.com/AppLovin/iOS-SDK-Demo/blob/master/Swift%20Demo%20App/iOS-SDK-Demo/ALDemoInterstitialBasicIntegrationViewController.swift)
- [Rewarded Ads](https://github.com/AppLovin/iOS-SDK-Demo/blob/master/Swift%20Demo%20App/iOS-SDK-Demo/ALDemoRewardedVideosViewController.swift)
- [Banners](https://github.com/AppLovin/iOS-SDK-Demo/blob/master/Swift%20Demo%20App/iOS-SDK-Demo/ALDemoProgrammaticBannerViewController.swift)
- [MRecs](https://github.com/AppLovin/iOS-SDK-Demo/blob/master/Swift%20Demo%20App/iOS-SDK-Demo/ALDemoProgrammaticMRecViewController.swift)
- [Native Ads](https://github.com/AppLovin/iOS-SDK-Demo/blob/master/Swift%20Demo%20App/iOS-SDK-Demo/ALDemoNativeAdProgrammaticViewController.swift)


I'll be closing the issue. Let me know if you have any further questions.


-Thomas
