### ISSUE TITLE
No such file or directory: 'ObjC'

### ISSUE THREAD

**Issue by nazmulkp** [AppLovin/iOS-SDK-Demo#25]
I flowing this tutorial but unfortunate I got a error that is 

> clang: error: no such file or directory: 'ObjC'

<img width="1011" alt="screen shot 2018-12-03 at 3 41 09 pm" src="https://user-images.githubusercontent.com/8841075/49365831-fadb9780-f711-11e8-9b77-f8e9885c7394.png">

<img width="590" alt="screen shot 2018-12-03 at 3 54 43 pm" src="https://user-images.githubusercontent.com/8841075/49366573-d41e6080-f713-11e8-9840-be9e419d9bd8.png">

**Project structure** 

<img width="258" alt="screen shot 2018-12-03 at 3 57 04 pm" src="https://user-images.githubusercontent.com/8841075/49366715-30818000-f714-11e8-86a4-ee0916130134.png">

How can I do this **The -ObjC flag must be added for static libraries (such as our SDK) to run correctly.** may be I miss this?

**Comment by thomasmso** [comment]
You have to include the `-` before the `ObjC`. Please see attached screenshot for reference.

![image](https://user-images.githubusercontent.com/5104410/49401642-a24dcf80-f6fc-11e8-93fd-3c227b554d2e.png)
