### ISSUE TITLE
Banner failed to load with error code 204

### ISSUE THREAD

**Issue by Prerna2929** [AppLovin/iOS-SDK-Demo#26]
I followed the all steps given in AppLovin SDK for ads integration. But i am facing error in Banner Ads. Banner Ads was worked only 4 - 5 times and than its started showing error message "Banner failed to load with error code 204". I am not able to understand that what is an issue. I am stuck due to this issue. I need to upload application on app store. 
Can anyone please help me with this issue ?

Thanks in advance

**Comment by thomasmso** [comment]
Could you try resetting your IDFA?

**Comment by Prerna2929** [comment]
HI @thomasmso ,
Thank you for giving reply.
Are you referring IDFA to make it enabled when we publish app to app store. But i am getting error "Banner failed to load with error code 204". in development phase with test mode. 
Banner ads is  showing 4 - 5 times per day and than returning this 204 error message.
Can you please help mw with this issue?

Thanks in advance.

**Comment by thomasmso** [comment]
1. Go to your "Settings" app -> Privacy -> Advertising -> "Reset Advertising Identifier".
2. Delete the app from your device, and re-run.

**Comment by Prerna2929** [comment]
Hi @thomasmso ,
Thank you for giving reply.
But this solution is not feasible for live user. App showing Banner ads only 6 time after fresh installation of app. Than it started showing error message 204. If i delete application and  again reinstall it, app started showing Banner ads and it will display  5 -6 times only and than again started showing error 204. 
Can you please update me is anything missed by us to manage from my side?
As such i also test the swift demo app provided on Git hub. And demo app also having same issue .
I can not figure out the solution for this issue. 
Would you please help me with this issue ? What can be permanent solution for this issue?
Looking forward to your reply.
Thanks in advance.

**Comment by thomasmso** [comment]
So that's because of [frequency capping rules](https://www.google.com/search?q=display+advertising+frequency+cap&rlz=1C5CHFA_enUS707US707&oq=advertising+frequency+cap&aqs=chrome.3.69i57j69i64j0l4.5676j1j1&sourceid=chrome&ie=UTF-8). It's not an "issue" per say. So I will close issue now.
