### ISSUE TITLE
Rewarded video show black screen for 3~5 seconds before showing ad.

### ISSUE THREAD

**Issue by cunzhegao** [AppLovin/iOS-SDK-Demo#29]
I'm using the latest SDK, and when I present a reward video ad, the presented controller would stay as black screen for about 3~5 seconds before showing the actually ad content. Is this expected behavior?

**Comment by thomasmso** [comment]
Hi. Are you on WiFi while testing? Are you on a fast network or throttling?

**Comment by cunzhegao** [comment]
I was on cellular network. I tested on other placements and it seems like only certain ads have this issue.

**Comment by thomasmso** [comment]
If you can retrieve [logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK) - that would help us track down the bad creative.

**Comment by cunzhegao** [comment]
OK, I'll try to reproduce the problem with verbose enabled. Also, below are screenshots of the ad I took from last time.

![IMG_3209](https://user-images.githubusercontent.com/19347161/56940364-79612780-6b40-11e9-9984-ea654ec5a90b.jpg)
![IMG_3210](https://user-images.githubusercontent.com/19347161/56940282-efb15a00-6b3f-11e9-82ba-b0ebf134fdcd.jpg)

**Comment by thomasmso** [comment]
Yes, our creatives may technically be served in different ways so we’ll need logs. Thanks!

**Comment by thomasmso** [comment]
Closing issue - free free to send our [SDK's verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK-) over to support@applovin.com if you are still experiencing this issue.
