### ISSUE TITLE
403 error when attempting to load an ad of any type in the demo

### ISSUE THREAD

**Issue by lveecode** [AppLovin/iOS-SDK-Demo#38]
1. Added my key to the AppLovinSdkKey field in the Info.plist
2. Added 'ALSdk.shared()!.settings.isTestAdsEnabled = true' to enable test ads (this ought to be enabled in a demo by default)
3. Any attempt to load an ad responds with a 403 error, all ad types

```
Log: [AppLovinSdk] DEBUG [ALConnectionManager] 403 received from "https://a.applovin.com/4.0/ad? [...] ": <HTML><HEAD>
<TITLE>403 Forbidden</TITLE>
</HEAD><BODY>
<H1>Forbidden</H1>
</BODY></HTML>
```

**Comment by thomasmso** [comment]
Please make sure that your bundle id, SDK key, and possibly ad zone id are correct.

Also, we're removing the `isTestAdsEnabled` API in the next release - as some publishers pushed their apps with that setting enabled. Please turn on test ads from your dashboard.

**Comment by lveecode** [comment]
Thanks, changing bundle id helped. 

> Also, we're removing the isTestAdsEnabled API in the next release - as some publishers pushed their apps with that setting enabled

>test mode takes up to 45 minutes to activate and lasts for 2 hours

So now each time QA needs to test the debug build of the app they need to wait 45 minutes, and carefully time testing so it doesn't exceed 2 hours (so that no invalid impressions are generated), all because some publishers pushed their apps with debug mode enabled? This seems extreme, to say the least. 

But I understand that this is outside the scope of this ticket, I'm closing it.
