### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tonywan2013** [AppLovin/iOS-SDK-Demo#39]
Dear Support,

If ALDemoBannerZoneViewController resides as second view using Navigation controller, ALDemoBannerZoneViewController is holding a strong reference of ALAdView as adView and ALAdView is also holding a strong reference to adView inside, causing a strong retain cycle.

It is expected to have user's VC to hold a strong reference and ALAdView should hold a weak reference only.

Please check.

Regards,
Tony

**Comment by thomasmso** [comment]
Thanks for bringing this up. We understand your concern but we can't flip the attribute now. We'll likely update the demo app this week to reflect what publishers should do when the view controller is dismissed.

**Comment by tonywan2013** [comment]
Dear Thomas,

Thanks for your quick response.

Regards,
Tony

**Comment by thomasmso** [comment]
Fixed: https://github.com/AppLovin/iOS-SDK-Demo/pull/40
