### ISSUE TITLE
Crash in AppLovin SDK 6.11.0

### ISSUE THREAD

**Issue by harturkm** [AppLovin/iOS-SDK-Demo#41]
Hi! We faced an issue in AppLovin SDK 6.11.0 :
![image](https://user-images.githubusercontent.com/36700413/79114184-4cc31180-7d8b-11ea-92ed-1d1fc1939d53.png)
It has affected iOS 13.3.1 and 13.4.1, only on iPhone 6s, 7 and 8. We have not been able to reproduce it yet, it does not seem to be a common crash. It seems around 0.1% - 0.4% of sessions experience this crash.
Could you check it, please?

**Comment by thomasmso** [comment]
Hello! This has been fixed in our latest iOS SDK (v6.12.1). Thank you!
