### ISSUE TITLE
Readme Clarification

### ISSUE THREAD

**Issue by jpsoultanis** [AppLovin/iOS-SDK-Demo#8]
Add instructions in the Readme to check off "Copy Items if Needed" when dragging and dropping the framework into the Demo project. Project won't compile otherwise, frameworks need their own code, not just references, to be independent.

**Comment by thomasmso** [comment]
Thanks for the input, we'll update our README file accordingly this week.

**Comment by thomasmso** [comment]
README file updated accordingly now. Thanks again!
